### ISSUE TITLE
Uncaught Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by seanhharrison** [joeferraro/MavensMate-Atom#120]
Uncaught Error: listen EADDRINUSE

**Atom Version**: 0.162.0
**System**: Mac OS X 10.10.1
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.13

### Steps To Reproduce??

1. I changed default metadata types default from "ApexClass, CustomObject" to "ApexClass,ApexPage,ApexTrigger,CustomObject,PermissionSet,Profile"
2. Created new project
3. After successful project creation, used Edit Project, then Advanced tab
4. Was distracted addressing another issue thread here :-)
5. When I returned, MM window was gone.
6. Closed all windows; Opened a new one
7. Red Atom Err window popped up

Doubtful I could reproduce this

### Stack Trace

```
At events.js:85

Error: listen EADDRINUSE
  at exports._errnoException (util.js:742:11)
  at Server._listen2 (net.js:1127:14)
  at listen (net.js:1153:10)
  at Server.listen (net.js:1238:5)
  at UIServer.startServer (/Users/seanharrison/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:283:19)
  at /Users/seanharrison/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:56:12
  at Server.onListen (/Users/seanharrison/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/portfinder/lib/portfinder.js:48:5)
  at Server.g (events.js:199:16)
  at Server.emit (events.js:104:17)
  at net.js:1142:12
  at process._tickDomainCallback (node.js:409:11)

```

/cc @atom/core

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
