### ISSUE TITLE
Visualforce live preview: Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by halldor-kaptio** [joeferraro/MavensMate-Atom#122]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.14

### Steps To Reproduce

1. Select "Mavensmate: Visualforce Live Preview" from Atom command palette

### Stack Trace

```
At /Users/halldor/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/client.js:183

TypeError: undefined is not a function
  at [object Object].Client.executeCommand (/Users/halldor/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/client.js:183:25)
  at MavensMateCoreAdapter.executeCommand (/Users/halldor/.atom/packages/MavensMate-Atom/lib/mavensmate-core-adapter.coffee:96:13)
  at atom-workspace.<anonymous> (/Users/halldor/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:263:40)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by jwreedy** [comment]
Is this feature available now?
