### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by agentgill** [joeferraro/MavensMate-Atom#130]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.9.5
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.14

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:516

TypeError: Cannot read property 'style' of undefined
  at [object Object].$.fn.isHidden (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:516:20)
  at [object Object].$.fn.isVisible (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:511:18)
  at MavensMateErrorMarkers.module.exports.MavensMateErrorMarkers.refreshMarkers (/Users/michael.gill/.atom/packages/MavensMate-Atom/lib/mavensmate-error-markers.coffee:26:27)
  at new MavensMateErrorMarkers (/Users/michael.gill/.atom/packages/MavensMate-Atom/lib/mavensmate-error-markers.coffee:13:6)
  at /Users/michael.gill/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:288:39
  at WorkspaceView.module.exports.WorkspaceView.eachEditorView (/Applications/Atom.app/Contents/Resources/app/src/workspace-view.js:92:9)
  at MavensMate.module.exports.MavensMate.initializeProject (/Users/michael.gill/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:286:26)
  at MavensMate.module.exports.MavensMate.onProjectPathChanged (/Users/michael.gill/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:127:10)
  at /Users/michael.gill/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:113:43
  at Project.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app/src/project.js:216:12)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:38:25)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
     -0:00.0 mavensmate:open-project (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {},
  "MavensMate-Atom": {
    "mm_workspace": [
      "Users/michael.gill/Dropbox/workspaces/fireeye/atom"
    ],
    "mm_panel_height": 346
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.14

# Dev
No dev packages
```

/cc @atom/core

**Comment by surfous** [comment]
I get this, too.
MacOS X 10.10.2
Atom 0.175
MM-atom 0.0.14

Happens when opening an existing project or when it opens a newly created project

Definitely a showstopper for using mm-atom. Only the Atom version changed when this error surfaced. MM was previously working at 0.0.14 after patching mavensmate.coffee for the SHA1/SHA256 issue, so first suspect seems to be Atom 0.175 +

**Comment by joeferraro** [comment]
There have been a slew of deprecations and changes in the underlying Atom APIs over the past 2 months. I'm on the verge of releasing an updated version of the package with several enhancements and fixes (this issue included)

**Comment by joeferraro** [comment]
FYI, I've pushed v0.0.15 of the package which resolves several issues and starts the long arduous process of updating deprecated atom references: https://atom.io/packages/mavensmate-atom

**Comment by joeferraro** [comment]
@surfous @agentgill did 0.0.15 resolve this for you guys?

**Comment by surfous** [comment]
@joeferraro yes, I can confirm as of this morning that 0.0.15 resolved this issue for me as well. w00t!

Thanks Joe!

**Comment by joeferraro** [comment]
:+1:

**Comment by jimrae** [comment]
@joeferraro I also am receiving this error.  Is there a way to upgrade to the 0.0.15 release?  If I run the upgrade installed packaged function, it says no packages to upgrade.

**Comment by seanhharrison** [comment]
Atom thinks you have the latest. Uninstall .14, restart Atom, then install MM. You should be good.

**Comment by jimrae** [comment]
Thank you @seanhharrison
