### ISSUE TITLE
Exception when running "New Resource Bundle" from the command palette: Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by NemSavic** [joeferraro/MavensMate-Atom#134]
[Enter steps to reproduce below:]

1. Try to call 'New Resource Bundle'

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.15

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Users/NemSavic/.atom/packages/MavensMate-Atom/lib/mavensmate-util.coffee:37

TypeError: Cannot read property 'split' of undefined
  at Function.module.exports.MMUtil.extension (/Users/NemSavic/.atom/packages/MavensMate-Atom/lib/mavensmate-util.coffee:37:21)
  at Function.module.exports.MMUtil.getSelectedFiles (/Users/NemSavic/.atom/packages/MavensMate-Atom/lib/mavensmate-util.coffee:73:17)
  at atom-workspace.<anonymous> (/Users/NemSavic/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:210:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Users/NemSavic/.atom/packages/MavensMate-Atom/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Users/NemSavic/.atom/packages/MavensMate-Atom/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  2x -1:07.9 core:move-up (atom-text-editor.editor.mini)
  2x -1:07.4 core:move-down (atom-text-editor.editor.mini)
  2x -1:06.9 core:move-up (atom-text-editor.editor.mini)
  2x -1:06.5 core:move-down (atom-text-editor.editor.mini)
  2x -1:05.7 core:move-up (atom-text-editor.editor.mini)
  2x -1:05.2 core:move-down (atom-text-editor.editor.mini)
  2x -1:04.8 core:move-up (atom-text-editor.editor.mini)
     -1:03.6 core:confirm (atom-text-editor.editor.mini)
     -0:22.0 command-palette:toggle (button.btn.btn-sm.btn-default.btn-toggle-panel)
 13x -0:19.9 core:backspace (atom-text-editor.editor.mini)
     -0:17.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:17.4 core:cancel (atom-text-editor.editor.mini)
     -0:11.6 command-palette:toggle (atom-text-editor.editor.is-focused)
 14x -0:06.7 core:backspace (atom-text-editor.editor.mini)
     -0:00.9 core:confirm (atom-text-editor.editor.mini)
     -0:00.9 mavensmate:new-resource-bundle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "flatland-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/NemSavic/Development/Workspace/Atom"
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/NemSavic/Development/Workspace/Atom"
    ],
    "mm_template_location": "local",
    "mm_panel_height": 155
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.15
docblockr, v0.5.8
flatland-dark-ui, v0.2.3
monokai, v0.12.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by joeferraro** [comment]
In order to create a new resource bundle, right click on a Static Resource in the project tree.

**Comment by nem604** [comment]
This works, thank you!
