### ISSUE TITLE
Uncaught TypeError: Cannot read property 'CustomObject' of null

### ISSUE THREAD

**Issue by sMaDyK** [joeferraro/MavensMate-Atom#138]
**Atom Version**: 0.177.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.15

### Stack Trace

Uncaught TypeError: Cannot read property 'CustomObject' of null

```
At C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\lib\mavensmate\index.js:64

TypeError: Cannot read property 'CustomObject' of null
  at C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\lib\mavensmate\index.js:64:33
  at Parser.<anonymous> (C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\xml2js\lib\xml2js.js:384:20)
  at Parser.emit (events.js:116:17)
  at Parser.exports.Parser.Parser.parseString (C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\xml2js\lib\xml2js.js:399:14)
  at Parser.parseString (C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\xml2js\lib\xml2js.js:6:61)
  at exports.parseString (C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\xml2js\lib\xml2js.js:433:19)
  at EventEmitter.<anonymous> (C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\lib\mavensmate\index.js:62:13)
  at EventEmitter.emit (events.js:119:17)
  at onstat (C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\findit\index.js:182:21)
  at C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\findit\index.js:133:22
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -3:24.4 mavensmate:new-project (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "D:\\SalesForce\\Mavensmate\\ATOM workspace"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.15

# Dev
No dev packages
```

/cc @atom/core

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
