### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clean' of undefined

### ISSUE THREAD

**Issue by surfous** [joeferraro/MavensMate-Atom#152]
[Enter steps to reproduce below:]

1. Just updated to Atom 0.181, but hadn't done a project clean in a while
2. Had just started Atom, Used MM Open Project to open a project created in an earlier version of MM (0.0.15, I think)
3. Went to run a Clean Project, confirmed action in dialog, and error occurred. 

**Atom Version**: 0.181.0
**System**: Mac OS X 10.10.2
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.18

### Stack Trace

Uncaught TypeError: Cannot read property 'clean' of undefined

```
At /Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/commands/project/clean-project.js:17

TypeError: Cannot read property 'clean' of undefined
  at Command.execute (/Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/commands/project/clean-project.js:17:20)
  at [object Object].Client.executeCommand (/Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/client.js:225:26)
  at MavensMateCoreAdapter.executeCommand (/Users/kshuk/.atom/packages/MavensMate-Atom/lib/mavensmate-core-adapter.coffee:152:13)
  at atom-workspace.<anonymous> (/Users/kshuk/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:240:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:69:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -0:15.3 mavensmate:open-project (atom-text-editor.editor)
     -0:03.3 mavensmate:clean-project (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "open-on-github"
    ],
    "themes": [
      "unity-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/Users/kshuk/Dropbox/Code/git"
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/kshuk/Documents/workspaces/mavensmate-atom"
    ],
    "mm_default_subscription": [
      "ApexClass",
      "ApexComponent",
      "ApexPage",
      "ApexTrigger",
      "CustomObject",
      "Profile",
      "StaticResource"
    ],
    "mm_panel_height": 41
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.18
atom-ctags, v2.6.0
autocomplete-plus, v2.1.6
docblockr, v0.5.8
language-groovy, v0.3.0
language-salesforce, v0.5.1
project-manager, v1.15.5
refactor, v0.4.1
rest-client, v0.3.1
script, v2.16.0
smarter-delete-line, v1.0.0
unity-ui, v2.0.2
visual-bell, v1.0.0

# Dev
No dev packages
```

**Comment by joeferraro** [comment]
0.0.19 attempts to resolve this issue

**Comment by surfous** [comment]
Works for me now - awesome!

BTW, I verified a repro on 0.0.18 just before updating to 0.0.19, so I know that it’s working on the same project where I’d experienced the error previously.

**Comment by joeferraro** [comment]
@surfous thanks for re-testing.
