### ISSUE TITLE
Uncaught Error: RefreshDelegate requires a valid project instance and an array of paths to refresh.

### ISSUE THREAD

**Issue by arpanvpatel** [joeferraro/MavensMate-Atom#154]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.181.0
**System**: Mac OS X 10.10.2
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.18

### Stack Trace

Uncaught Error: RefreshDelegate requires a valid project instance and an array of paths to refresh.

```
At /Users/arpanpatel/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/refresh.js:22

Error: RefreshDelegate requires a valid project instance and an array of paths to refresh.
  at new RefreshDelegate (/Users/arpanpatel/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/refresh.js:22:11)
  at Command.execute (/Users/arpanpatel/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/commands/metadata/refresh-metadata.js:22:25)
  at [object Object].Client.executeCommand (/Users/arpanpatel/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/client.js:225:26)
  at MavensMateCoreAdapter.executeCommand (/Users/arpanpatel/.atom/packages/MavensMate-Atom/lib/mavensmate-core-adapter.coffee:152:13)
  at atom-workspace.<anonymous> (/Users/arpanpatel/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:240:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:74:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:147:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -5:01.5 mavensmate:open-project (atom-text-editor.editor)
     -4:38.1 settings-view:uninstall-packages (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -4:27.9 core:backspace (atom-text-editor#MavensMate-Atom.mm_atom_exec_path.editor.mini)
     -4:25.7 core:save (div.settings-view.pane-item)
     -4:13.2 settings-view:uninstall-packages (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Applications/AtomWorkspace"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.18

# Dev
No dev packages
```

**Comment by joeferraro** [comment]
Please provide steps to reproduce

**Comment by arpanvpatel** [comment]
Just created new project and when try to refresh any class, its giving this error

**Comment by arpanvpatel** [comment]
Open Project > Select Project as you want to select > src  > classes > Select Class as want to modify > Right click and choose "Mavensmate" > Refresh from Server
And getting this error.

**Comment by joeferraro** [comment]
did you wait for the project to initialize?

**Comment by cpurodriguez** [comment]
@joeferraro @arpanvpatel I'm having the same error, and project initialization never ends

Attaching deprecation cop messages

![deprecated selectors](https://cloud.githubusercontent.com/assets/751452/6275432/2b73a610-b866-11e4-975c-e6651cb19701.png)

**Comment by arpanvpatel** [comment]
I have same issue its still saying Initializing Mavens-mate Project

**Comment by arpanvpatel** [comment]
![74d870d8-b848-11e4-9002-73f3880d894d](https://cloud.githubusercontent.com/assets/11077969/6276711/69e16ee0-b84e-11e4-976c-dea1f2b41280.png)

**Comment by jonathanstegall** [comment]
I'm having this as well. Perhaps it might be related to another Atom update (mine updated itself yesterday).

**Comment by joeferraro** [comment]
unfortunately it is...atom.project.path has been deprecated without notice to atom.project.getPath. i'll be pushing an update soonest #smh

**Comment by joeferraro** [comment]
0.0.19 attempts to resolve this issue

**Comment by arpanvpatel** [comment]
@joeferraro  Great job. It's working fine now.
