### ISSUE TITLE
"The requested resource does not exist" error

### ISSUE THREAD

**Issue by jpmonette** [joeferraro/MavensMate-Atom#162]
When I try to create a project, I get the following error message: `The requested resource does not exist`. I do also use Sublime Text and I do not get this issue, so I suppose it is Atom-specific.

## Steps to reproduce

1. Click on `MavensMate > Project > New Project`
2. Populate `Project Details`, using a sandbox environment in my case
3. Click on `Project Metadata`
4. Select Apex Classes and Triggers needed (select all checkboxes, but I can drill down and see existing metadata)
5. Click on `Create Project`

Expected outcome: Creating a new project
Actual outcome: Returning error message `The requested resource does not exist`

---

Platform: `OSX`
Atom version: `0.186.0`
Mavensmate for Atom version: `0.0.20`

---

Thanks for this great tool!

**Comment by joeferraro** [comment]
interesting, can you enable logging for MavensMate-Atom?

1. go to package settings for MavensMate-Atom
2. set plugin log level to SILLY
3. set plugin debug logs location to an existing path on your machine
4. restart atom
5. retry your operation
6. paste log to this issue

**Comment by jpmonette** [comment]
```
==================> executing command: new-project

2015-03-06T15:42:00.478Z - debug: payload is: {"name":"Project Name","username":"valid@user.name","password":"somePassword","orgType":"sandbox","package":{"ApexClass":"*","ApexComponent":"*","ApexPage":"*","ApexTrigger":"*"},"workspace":"/Users/jpmonette/Development/atom-workspace","subscription":["ApexClass","ApexComponent","ApexPage","ApexTrigger","StaticResource"],"action":"new","instanceUrl":""}
2015-03-06T15:42:00.478Z - debug: command class is: NewProjectCommand
2015-03-06T15:42:00.480Z - debug: initiating SalesforceClient: 
2015-03-06T15:42:00.480Z - debug: initializing connection to salesforce ...
2015-03-06T15:42:00.482Z - debug: initing connection via login ...
2015-03-06T15:42:00.482Z - debug: logging in to salesforce: https://test.salesforce.com/
2015-03-06T15:42:01.653Z - debug: getting user information:
2015-03-06T15:42:02.175Z - debug: logged in successfully
2015-03-06T15:42:02.175Z - debug: configuring jsforce ...
2015-03-06T15:42:03.002Z - debug: Initiated new project, prepping to write to disk
2015-03-06T15:42:03.964Z - debug: retrieving unpackaged: 
2015-03-06T15:42:03.964Z - debug:  ApexClass=*, ApexComponent=*, ApexPage=*, ApexTrigger=*
2015-03-06T15:42:28.262Z - debug: writing local session
2015-03-06T15:42:28.262Z - debug:  accessToken=someValidToken, instanceUrl=https://cs17.salesforce.com
2015-03-06T15:42:28.264Z - debug: indexing lightning to config/.lightning
2015-03-06T15:42:28.887Z - error: Could not index lightning -->The requested resource does not exist
2015-03-06T15:42:28.888Z - error: Could not initiate project config directory -->The requested resource does not exist
2015-03-06T15:42:28.955Z - error: Could not retrieve and write project to file system: The requested resource does not exist
2015-03-06T15:42:28.955Z - error: NOT_FOUND: The requested resource does not exist
  at onResponse (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/connection.js:368:13)
  at _fulfilled (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:798:54)
  at self.promiseDispatch.done (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:827:30)
  at Promise.promise.promiseDispatch (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:760:13)
  at /Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:574:44
  at flush (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:364:11)

2015-03-06T15:42:28.956Z - debug: Could not create project: 
2015-03-06T15:42:28.956Z - debug: NOT_FOUND: The requested resource does not exist
  at onResponse (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/connection.js:368:13)
  at _fulfilled (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:798:54)
  at self.promiseDispatch.done (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:827:30)
  at Promise.promise.promiseDispatch (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:760:13)
  at /Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:574:44
  at flush (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:364:11)

2015-03-06T15:42:28.956Z - debug: response: 
2015-03-06T15:42:28.956Z - debug:  result=Could not create project, error=The requested resource does not exist, stack=NOT_FOUND: The requested resource does not exist
  at onResponse (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/connection.js:368:13)
  at _fulfilled (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:798:54)
  at self.promiseDispatch.done (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:827:30)
  at Promise.promise.promiseDispatch (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:760:13)
  at /Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:574:44
  at flush (/Users/jpmonette/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:364:11)
```

**Comment by joeferraro** [comment]
ah ok, i see it now, looks like it's barfing when trying to index lightning metadata in an org that isn't lightning-enabled. thanks
