### ISSUE TITLE
Failed to activate the MavensMate-Atom package

### ISSUE THREAD

**Issue by aluukka** [joeferraro/MavensMate-Atom#179]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.20

### Stack Trace

Failed to activate the MavensMate-Atom package

```
At undefined is not a function

TypeError: undefined is not a function
  at MavensMate.module.exports.MavensMate.initializeProject (/Users/aku/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:115:23)
  at MavensMate.module.exports.MavensMate.init (/Users/aku/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:83:12)
  at new MavensMate (/Users/aku/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:56:8)
  at Object.module.exports.activate (/Users/aku/.atom/packages/MavensMate-Atom/lib/main.coffee:147:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:302:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:414:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:395:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:634:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:54:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "color-picker",
      "autocomplete-html",
      "emmet",
      "language-salesforce"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/aku/worspace"
    ],
    "mm_use_keyring": false,
    "mm_panel_height": 189
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.20

# Dev
No dev packages
```

**Comment by praneel** [comment]
I have the same problem 

Atom 
Version 0.206.0 (0.206.0)

Error Message

Failed to activate the MavensMate-Atom package

![Uploading Screen Shot 2015-06-05 at 13.43.44.png…]()

undefined is not a function
Hide Stack Trace
TypeError: undefined is not a function
  at MavensMate.module.exports.MavensMate.initializeProject (/Users/praneelpidikiti/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:115:23)


Any workaround ?

**Comment by orospakr** [comment]
This suddenly started happening for me when I restarted Atom after an attempt to save an Apex class hung.  Now the project doesn't open at all, instead failing with the above traceback.

That line is attempting to use `atom.project.getPath()` which is deprecated API, and iirc the Atom team did warn of dropping lots of deprecated APIs in "early June", which is now.

**Comment by orospakr** [comment]
I went through and changed all usages of `getPath()` to `getPaths()[0]`, which was in about 4 places in two files (mavensmate.coffee and util.coffee), and that seems to have got things limping forward again.  Obviously that is not a correct fix, though.

Incidentally, I had temporarily added another "project folder" to my project yesterday, and I think that's what's brought this on (Atom disabled some old API when multiple project folders were added, or something).

**Comment by venkatpolisetti** [comment]
Started having issues with MavensMate on OSX 10.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.21


### Stack Trace

Failed to activate the MavensMate-Atom package

```
At undefined is not a function

TypeError: undefined is not a function
  at MavensMate.module.exports.MavensMate.initializeProject (/Users/venkatpolisetti/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:115:23)
  at MavensMate.module.exports.MavensMate.init (/Users/venkatpolisetti/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:83:12)
  at new MavensMate (/Users/venkatpolisetti/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:56:8)
  at Object.module.exports.activate (/Users/venkatpolisetti/.atom/packages/MavensMate-Atom/lib/main.coffee:147:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -3:52.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:35.7.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/venkatpolisetti/Documents/mavensmate/atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.21
atom-alignment, v0.12.1
auto-reveal-in-sidebar, v0.5.0
change-case, v0.6.0
emmet, v2.3.10
jshint, v1.3.7
language-salesforce, v0.6.0
minimap, v4.9.4
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by rphil** [comment]
I get the error when opening Atom. However, a project can still be created. It will never open.

<h2>Error</h2>
    Failed to activate the MavensMate-Atom package
    undefined is not a function
    Hide Stack Trace
    TypeError: undefined is not a function
     at MavensMate.module.exports.MavensMate.initializeProject (/Users/rp/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:115:23)
     at MavensMate.module.exports.MavensMate.init (/Users/rp/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:83:12)
      at new MavensMate (/Users/rp/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:56:8)
      at Object.module.exports.activate (/Users/rp/.atom/packages/MavensMate-Atom/lib/main.coffee:147:23)
      at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
      at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
      at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
      at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
      at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
      at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
      at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
      at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
      at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
      at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:636:21)
      at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
      at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
      at Module._compile (module.js:452:26)
      at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
      at Module.load (module.js:347:32)
      at Function.Module._load (module.js:302:12)
      at Module.require (module.js:357:17)
      at require (module.js:376:17)
      at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:95:23)
      at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

<h2>Config</h2>

    "*":
      "exception-reporting":
       userId: "redacted"
      welcome:
       showOnStartup: false
      core:
        themes: [
          "sepia-light-ui"
          "solarized-light-syntax"
        ]
      editor:
        invisibles:
          {}
      "MavensMate-Atom":
        mm_api_version: "33"
        mm_default_subscription: [
          "ApexClass"
          "ApexComponent"
          "ApexPage"
          "ApexTrigger"
          "StaticResource"
          "CustomObject"
        ]
        mm_workspace: [
          "/Users/rp/Documents/Workspace/Project/QG"
          "/Users/rp/Documents/Workspace/Project/LZ"
          "/Users/rp/Documents/Workspace/Project/XR"
          "/Users/rp/Documents/Workspace/Project/Dev"
          "/Users/rp/Documents/Workspace/Project/Apps"
          "/Users/rp/Documents/Workspace/Project/RPC"
        ]

**Comment by chrishickman81** [comment]
Same problem, happened when I updated Mavensmate and Atom today to the latest available versions.

**Comment by joeferraro** [comment]
https://github.com/joeferraro/MavensMate-Atom/commit/8fead8fcf46101a87e2f8de88d43ea6d5b8d8a63 closes this issue
