### ISSUE TITLE
Failed to load the MavensMate-Atom package

### ISSUE THREAD

**Issue by shaynefPCS** [joeferraro/MavensMate-Atom#182]
[Enter steps to reproduce below:]

1. ... New Atom Install
2. ... Install Git
3. ... Attempt mavensmate install without restart.

**Atom Version**: 0.190.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.20

### Stack Trace

Failed to load the MavensMate-Atom package

```
At Cannot find module 'underscore'

Error: Cannot find module 'underscore'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\node_modules\underscore-plus\lib\underscore-plus.js:5:7)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\node_modules\underscore-plus\lib\underscore-plus.js:522:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:8:9)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:634:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\node_modules\atom-space-pen-views\lib\main.js:4:10)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\node_modules\atom-space-pen-views\lib\main.js:22:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\lib\mavensmate.coffee:1:25)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\lib\mavensmate.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\lib\main.coffee:1:26)
  at Object.<anonymous> (C:\Users\shayn_000\.atom\packages\MavensMate-Atom\lib\main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:665:34)
  at C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:174:28
  at Package.module.exports.Package.measure (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:152:15)
  at Package.module.exports.Package.load (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:166:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\package-manager.js:355:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\package-manager.js:325:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\atom.js:631:21)
  at Object.<anonymous> (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\shayn_000\AppData\Local\atom\app-0.190.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///C:/Users/shayn_000/AppData/Local/atom/app-0.190.0/resources/app/static/index.js:54:25)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.20

# Dev
No dev packages
```

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!
