### ISSUE TITLE
Uncaught Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\grady\Documents\SourceControl\SalesForce\Personal SB\unpackaged\classes'

### ISSUE THREAD

**Issue by GradyD** [joeferraro/MavensMate-Atom#196]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.20

### Stack Trace

Uncaught Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\grady\Documents\SourceControl\SalesForce\Personal SB\unpackaged\classes'

```
At C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:103

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\grady\Documents\SourceControl\SalesForce\Personal SB\unpackaged\classes'
  at Error (native)
  at Object.fs.rmdirSync (fs.js:755:18)
  at rmkidsSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:247:11)
  at rmdirSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:150:5)
  at rimrafSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:216:26)
  at C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:244:26)
  at rmdirSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:150:5)
  at rimrafSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:216:26)
  at C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:244:26)
  at rmdirSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:150:5)
  at Function.rimrafSync (C:\Users\grady\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\rimraf\rimraf.js:216:26)
  at Object.rmrfSync (C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\fs-extra\lib\remove.js:7:19)
  at C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\lib\mavensmate\project.js:313:16
  at tryCatch1 (C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\util.js:45:21)
  at Promise._callHandler (C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:571:13)
  at Promise._settlePromiseFromHandler (C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:581:18)
  at Promise._settlePromiseAt (C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:733:18)
  at Promise._settlePromises (C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:845:14)
  at Async._consumeFunctionBuffer (C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:85:12)
  at Async.consumeFunctionBuffer (C:\Users\grady\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:40:14)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -4:46.1.0 mavensmate:new-project (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-pair"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "C:\\Users\\grady\\Documents\\SourceControl\\SalesForce"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0
highlight-selected, v0.9.3
MavensMate-Atom, v0.0.20
minimap, v4.9.0
project-manager, v1.15.7
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by GradyD** [comment]
Duplicate
