### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by johnnyfreeman** [joeferraro/MavensMate-Atom#205]
[Enter steps to reproduce below:]

1. right click on any file in sidebar
2. refresh from server

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.23

### Stack Trace

Uncaught TypeError: Cannot read property 'find' of undefined

```
At /Users/jfreeman/.atom/packages/MavensMate-Atom/lib/util.coffee:190

TypeError: Cannot read property 'find' of undefined
  at Function.module.exports.MMUtil.treeView (/Users/jfreeman/.atom/packages/MavensMate-Atom/lib/util.coffee:190:25)
  at Function.module.exports.MMUtil.getSelectedFiles (/Users/jfreeman/.atom/packages/MavensMate-Atom/lib/util.coffee:62:23)
  at atom-workspace.<anonymous> (/Users/jfreeman/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:216:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:148:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -5:19.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -5:19.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:16.4.0 core:cut (atom-text-editor.editor.is-focused)
     -1:13.1.0 core:paste (atom-text-editor.editor.is-focused)
  4x -1:10.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:48.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:48.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:48.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:44.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:43.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:42.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:35.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:31.7.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
  3x -0:29.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.8.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "atom-beautify"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.sublime-*"
    ],
    "projectHome": "/Users/jfreeman/Projects"
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/jfreeman/Projects/"
    ],
    "mm_panel_height": 208
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.23
Stylus, v1.0.0
build, vundefined
docblockr, v0.7.2
editorconfig, v1.0.0
emmet, v2.3.10
file-icons, v1.5.7
highlight-selected, v0.9.3
language-salesforce, v0.6.0
linter, v0.12.6
minimap, v4.9.4
react, v0.12.0

# Dev
No dev packages
```

**Comment by jdickertBHTP** [comment]
I have this same issue.
