### ISSUE TITLE
When opening a Salesforce Custom Object (.object) file: Uncaught TypeError: Cannot read property 'grammarForScopeName' of undefined

### ISSUE THREAD

**Issue by orospakr** [joeferraro/MavensMate-Atom#208]
1. Open a Mavensmate project;
2. Open up one of your custom object definitions (a `.object` file).

It looks like `undefined` is getting passed to the `atom.workspace.observeTextEditors` handler block inside MavensMate#initializeProject (line 130 of `mavensmate.coffee`).

Note: This can manifest a bit differently if you are re-opening a Mavensmate project that already had a tab open with a `.object` file: the error will appear in the bottom pane right on startup rather than an angry red Atom error toast:

![settings_-__users_orospakr_code_joist_salesforce-workspace_joist-salesforce_-_atom](https://cloud.githubusercontent.com/assets/16714/8061542/5a3823ca-0e99-11e5-9191-d4c67d40f931.png)

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.24

### Stack Trace

Uncaught TypeError: Cannot read property 'grammarForScopeName' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

TypeError: Cannot read property 'grammarForScopeName' of undefined
  at MavensMate.module.exports.MavensMate.registerGrammars (/Users/orospakr/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:259:40)
  at /Users/orospakr/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:132:20
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:272:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:375:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:326:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:297:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:472:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:03.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:02.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "ide-haskell",
      "language-haskell"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/orospakr/code/joist/salesforce-workspace"
    ],
    "mm_panel_height": 258
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.24
go-plus, v3.3.11
language-rust, v0.4.3
pretty-json, v0.3.3

# Dev
No dev packages
```

**Comment by orospakr** [comment]
Just an FYI, I'm still experiencing this issue.

Note that it only happens when a) reopening the project b) opening a custom object file via Command-P
