### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::8000

### ISSUE THREAD

**Issue by jeancdc** [joeferraro/MavensMate-Atom#213]
After updating to Atom 0.211, I've got this error:
```
events.js:141

Error: listen EADDRINUSE :::8000
  at Object.exports._errnoException (util.js:734:11)
  at exports._exceptionWithHostPort (util.js:757:20)
  at Server._listen2 (net.js:1173:14)
  at listen (net.js:1203:10)
  at Server.listen (net.js:1290:5)
  at UIServer.startServer (/Users/jeancreuzedeschatelliers/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:290:19)
  at /Users/jeancreuzedeschatelliers/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:63:12
  at Server.onListen (/Users/jeancreuzedeschatelliers/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/portfinder/lib/portfinder.js:48:5)
  at Server.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:163:7)
  at net.js:1192:12
  at process._tickCallback (node.js:357:13)
```

Mac OS X 10.10.3
Atom 0.211
MavensMate 0.0.24

Steps to reproduce : just launch Atom.

**Comment by jeancdc** [comment]
No problem anymore after close Atom, relaunch it and reopen Salesforce project.
