### ISSUE TITLE
Uncaught TypeError: Cannot read property 'inFolder' of undefined

### ISSUE THREAD

**Issue by axlemax** [joeferraro/MavensMate-Atom#234]
[Enter steps to reproduce below:]

1. Set up MavensMate project
2. Open project in Atom

**Atom Version**: 1.0.4
**System**: Mac OS X 10.10.3
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.24

### Stack Trace

Uncaught TypeError: Cannot read property 'inFolder' of undefined

```
At /Users/maxwella/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/project.js:904

TypeError: Cannot read property 'inFolder' of undefined
  at /Users/maxwella/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/project.js:904:35
  at Function.forEach (/Users/maxwella/.atom/packages/MavensMate-Atom/node_modules/lodash/dist/lodash.js:3297:15)
  at /Users/maxwella/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/project.js:903:19
  at Function.forOwn (/Users/maxwella/.atom/packages/MavensMate-Atom/node_modules/lodash/dist/lodash.js:2105:15)
  at /Users/maxwella/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/project.js:889:15
  at /Users/maxwella/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/fs-extra/node_modules/jsonfile/index.js:19:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "dracula-theme"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "wrap-guide"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/maxwella/Workspaces/"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.24
atom-alignment, v0.12.1
atom-html-preview, v0.1.11
color-picker, v2.0.11
dracula-theme, v0.7.6
file-icons, v1.6.2
highlight-selected, v0.10.1
language-salesforce, v0.6.0
minimap, v4.12.2
minimap-codeglance, v0.4.0
minimap-find-and-replace, v4.2.0
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.2
minimap-selection, v4.3.0
open-recent, v2.3.0
pigments, v0.9.3
project-manager, v1.15.11
revert-buffer, v0.5.0
symbols-tree-view, v0.9.3
unity-ui, v2.0.11

# Dev
No dev packages
```

**Comment by joeferraro** [comment]
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!

**Comment by garyspencer** [comment]
I also get this error after initial project creation:

1) Create Project
2) Right-click root folder, Mavens Mate, Refresh from server

Issue:  Error: ... 'inFolder' of undefined....

Solution: Restart SublimeText3.

**Comment by mratliffncino** [comment]
I'm getting this same error after restarting SublimeText3.  Mavensmate version 7.0.-beta3.

**Comment by iDev0urer** [comment]
If anyone is still getting this error while using Sublime Test 3 please put an issue in the MavensMate-SublimeText repo. This repo is solely for Atom
