### ISSUE TITLE
Could not run tests: The requested resource does not exist

### ISSUE THREAD

**Issue by nwoolls** [joeferraro/MavensMate-Atom#257]
I am trying to run Unit Tests from the Test Runner. It works just dandy in the Sublime package but not the Atom package. I get the following message in a div / alert in the Test Runner UI:

```Could not run tests: The requested resource does not exist```

**Comment by nwoolls** [comment]
More details from *SILLY* debug log level:

```
==================> executing command: run-tests

2015-09-18T01:33:37.935Z - debug: payload is: {"path":"/Users/nwoolls/workspaces/apex-connectors/sfdc-provisioning-connectors2","ui":true,"classes":["HttpCallTest"]}
2015-09-18T01:33:37.935Z - debug: command class is: RunTestsCommand
2015-09-18T01:33:37.938Z - debug: running the following tests: 
2015-09-18T01:33:37.938Z - debug:  ApexClassId=01p37000002WFi1AAG
2015-09-18T01:33:40.360Z - debug: response: 
2015-09-18T01:33:40.360Z - debug:  result=Could not run tests, error=Could not run tests: The requested resource does not exist, stack=Error: Could not run tests: The requested resource does not exist
  at /Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/test.js:129:16
  at tryCatch1 (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:45:21)
  at Promise._callHandler (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:571:13)
  at Promise._settlePromiseFromHandler (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:581:18)
  at Promise._settlePromiseAt (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:733:18)
  at Promise._settlePromises (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:845:14)
  at Async._consumeFunctionBuffer (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:85:12)
  at Async.consumeFunctionBuffer (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:40:14)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

2015-09-18T01:33:40.360Z - debug: async request finished with error
2015-09-18T01:33:40.361Z - debug: undefined
 ```

**Comment by nwoolls** [comment]
Tried enabling Logging from the MavensMate > Debug menu and get a similar error:

```
> Creating trace flags for user ids in config/.debug
> Could not start logging
{
  "result": "Could not start logging",
  "error": "Could not retrieve TraceFlags for debug users: The requested resource does not exist",
  "stack": "Error: Could not retrieve TraceFlags for debug users: The requested resource does not exist\n  at /Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/sfdc-client.js:798:16\n  at promiseCallback (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/query.js:332:15)\n  at [object Object].<anonymous> (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/query.js:348:5)\n  at [object Object].g (events.js:260:16)\n  at emitOne (events.js:77:13)\n  at [object Object].emit (events.js:169:7)\n  at /Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/query.js:378:10\n  at /Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/lib/core.js:33:15\n  at flush (/Users/nwoolls/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)\n  at doNTCallback0 (node.js:416:9)\n  at process._tickCallback (node.js:345:13)\n",
  "promiseId": "5534e680-5da7-11e5-bb97-0bc3791ed0c8"
}
```

**Comment by joeferraro** [comment]
please install 1.0.0 (which requires mavensmate-app: https://github.com/joeferraro/mavensmate-app/releases) and let me know if you still run into this issue. closing in the meantime.
