### ISSUE TITLE
MavensMate not compatible with this version of

### ISSUE THREAD

**Issue by Saul3d** [joeferraro/MavensMate-Atom#258]
The following packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

MavensMate-Atom 0.0.24
ATOM 1.0.13
Mac 10.10.5

Error Message:

sh: node: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/iiu7697/.atom/.apm/.apmrc" "--userconfig" "/Users/iiu7697/.atom/.apmrc" "rebuild" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mavensmate@0.0.37 postinstall: `node bin/postInstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mavensmate@0.0.37 postinstall script 'node bin/postInstall'.
npm ERR! This is most likely a problem with the mavensmate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/postInstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls mavensmate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iiu7697/.atom/packages/MavensMate-Atom/npm-debug.log

**Comment by jeancdc** [comment]
I've got problem too with the same version of Atom and MavensMate as Saul3d: 

```
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/keytar.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jeancreuzedeschatelliers/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/keytar
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jeancreuzedeschatelliers/.atom/.apm/.apmrc" "--userconfig" "/Users/jeancreuzedeschatelliers/.atom/.apmrc" "rebuild" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! keytar@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeancreuzedeschatelliers/.atom/packages/MavensMate-Atom/npm-debug.log
```

**Comment by surfous** [comment]
I've been hit by this as well.

MavensMate-Atom 0.0.24
Atom 1.0.15
MacOS X 10.10.5

I attempted the package rebuild and got the dump below, and my npm-debug.log is in this Gist: https://gist.github.com/surfous/2fbc0b83b5f6cfb9e066

```
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/keytar.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kshuk/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/keytar
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/kshuk/.atom/.apm/.apmrc" "--userconfig" "/Users/kshuk/.atom/.apmrc" "rebuild" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! keytar@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kshuk/.atom/packages/MavensMate-Atom/npm-debug.log
```

**Comment by joeferraro** [comment]
v1.0.0 no longer requires keytar, so this should not be an issue. please retry the install and let me know if you still run into issues
