### ISSUE TITLE
Creating Deploy Connection to a sandbox fails

### ISSUE THREAD

**Issue by harshal-gajare** [joeferraro/MavensMate-Atom#260]
I am trying to setup a new connection to a sandbox org but unable to add a connection . Seems like even if the option for sandbox is selected the connection is being made to login.salesforce.com

MavensMate-Atom 0.0.24 
Atom version 1.0.15
Mac OS X

015-09-19T01:50:10.523Z - debug: payload is: {"username":"username","password":"pass","org_type":"sandbox","command":"new-connection"}
2015-09-19T01:50:10.523Z - debug: command class is: NewConnectionCommand
2015-09-19T01:50:10.596Z - debug: initiating SalesforceClient: 
2015-09-19T01:50:10.596Z - debug: initializing connection to salesforce ...
2015-09-19T01:50:10.596Z - debug: initing connection via login ...
2015-09-19T01:50:10.596Z - debug: logging in to salesforce: https://login.salesforce.com/
2015-09-19T01:50:12.201Z - debug: error logging in: INVALID_LOGIN: Invalid username, password, security token; or user locked out.
2015-09-19T01:50:12.209Z - debug: response: 
2015-09-19T01:50:12.209Z - debug:  result=Could not add connection, error=Could not add org connection: Could not log in to Salesforce.com: Error: INVALID_LOGIN: Invalid username, password, security token; or user locked out., stack=Error: Could not add org connection: Could not log in to Salesforce.com: Error: INVALID_LOGIN: Invalid username, password, security token; or user locked out.
  at /Users/LM97580/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/org-connection.js:93:16
  at tryCatch1 (/Users/LM97580/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:45:21)
  at Promise._callHandler (/Users/LM97580/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:571:13)
  at Promise._settlePromiseFromHandler (/Users/LM97580/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:581:18)
  at Promise._settlePromiseAt (/Users/LM97580/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:733:18)
  at Promise._settlePromises (/Users/LM97580/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:845:14)
  at Async._consumeFunctionBuffer (/Users/LM97580/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:85:12)
  at Async.consumeFunctionBuffer (/Users/LM97580/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:40:14)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

**Comment by joeferraro** [comment]
this has been resolved in the core: https://github.com/joeferraro/MavensMate/issues/514
