### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/tak4hir0/.atom/packages/Mavens...

### ISSUE THREAD

**Issue by tak4hir0** [joeferraro/MavensMate-Atom#266]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v1.0.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/tak4hir0/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/controllers'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir '/Users/tak4hir0/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/controllers'
  at Error (native)
  at Object.fs.readdirSync (fs.js:813:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:449:28)
  at UIServer.startServer (/Users/tak4hir0/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:247:6)
  at /Users/tak4hir0/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:63:12
  at Server.onListen (/Users/tak4hir0/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/portfinder/lib/portfinder.js:48:5)
  at Server.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitListeningNT (net.js:1240:10)
  at doNTCallback1 (node.js:427:9)
  at process._tickCallback (node.js:349:17)

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "MavensMate-Atom": {
    "mm_compile_check_conflicts": true,
    "mm_workspace": [
      "/Users/tak4hir0/Workspaces/Atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v1.0.3
Sublime-Style-Column-Selection, v1.3.0
atom-html-preview, v0.1.11
compare-files, v0.6.2
emmet, v2.3.12
file-icons, v1.5.8
japanese-wrap, v0.2.7
language-salesforce, v0.6.0
linter, v1.2.4
minimap, v4.12.0

# Dev
No dev packages
```

**Comment by tak4hir0** [comment]
It was solved After installing the application.
https://github.com/joeferraro/mavensmate-app/releases

**Comment by joeferraro** [comment]
I've seen this before and it looks like it may be an Atom issue. If anyone runs into this in the future, my suggestion would be to uninstall then re-install the plugin.
