### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by silverskyvicto** [joeferraro/MavensMate-Atom#267]
I was trying to update the plug-in. Then the following error has occurred.

As far as the error message, it appears to cause that are going to see a folder that does not exist.

Please tell me what to do.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v1.0.3

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/ey/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/controllers'

```
At fs.js:805

Error: ENOENT: no such file or directory, scandir '/Users/ey/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/controllers'
  at Error (native)
  at Object.fs.readdirSync (fs.js:805:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:441:28)
  at UIServer.startServer (/Users/ey/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:247:6)
  at /Users/ey/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:63:12
  at Server.onListen (/Users/ey/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/portfinder/lib/portfinder.js:48:5)
  at Server.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:163:7)
  at net.js:1192:12
  at process._tickDomainCallback (node.js:384:13)

```

### Commands

```
     -7:04.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "MavensMate-Atom": {
    "mm_api_version": "34.0",
    "mm_workspace": [
      "/Users/ey/Documents/MMWorkspace"
    ]
  }
}
```

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate-Atom/issues/266

**Comment by Karankhatri** [comment]
Hi @joeferraro ,

I am trying to install the plugin "MavensMate-Atom" and getting this error:
s.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Karan Khatri\.atom\packages\MavensMate-Atom\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (C:\Users\Karan Khatri\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\asar-require\lib\require.js:86:27)
    at C:\Users\Karan Khatri\AppData\Local\atom\app-1.23.1\resources\app\apm\lib\install.js:476:42
    at fn (C:\Users\Karan Khatri\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\Karan Khatri\AppData\Local\atom\app-1.23.1\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
29,362

Can you please help me with that?
