### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/joaoamaral/.atom/packages/Mave...

### ISSUE THREAD

**Issue by joaoamaral** [joeferraro/MavensMate-Atom#273]
[Enter steps to reproduce below:]

1. Updating MavensMate-Atom to latest version from Atom

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v1.0.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/joaoamaral/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/controllers'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir '/Users/joaoamaral/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/controllers'
  at Error (native)
  at Object.fs.readdirSync (fs.js:813:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:449:28)
  at UIServer.startServer (/Users/joaoamaral/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:247:6)
  at /Users/joaoamaral/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:63:12
  at Server.onListen (/Users/joaoamaral/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/portfinder/lib/portfinder.js:48:5)
  at Server.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:166:7)
  at emitListeningNT (net.js:1240:10)
  at doNTCallback1 (node.js:427:9)
  at process._tickCallback (node.js:349:17)

```

### Commands

```
     -0:38 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v1.0.5
angularjs, v0.3.0
atom-color-highlight, v3.0.9
color-picker, v2.0.12
minimap, v4.13.4
monokai, v0.18.0
svg-preview, v0.6.1
tree-ignore, v0.2.6

# Dev
No dev packages
```

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate-Atom/issues/266
