### ISSUE TITLE
[Windows 10] Error when running 'Mavensmate: Start Logging'

### ISSUE THREAD

**Issue by DavinCasey** [joeferraro/MavensMate-Atom#285]
### Windows 10 / MavensMate-app v0.0.10 / Atom v.1.1.0

Logging doesn't seem to be working in this version of the app in Windows 10.

When running the start logging command, the following error is returned:
```
[November 1st 2015, 10:10:30 pm]
> Starting logging for users specified in config/.debug
> Could not create Trace Flags: LogType is required.: LogType
{
  "id": "5d274930-80e5-11e5-8a8b-03eee0688405",
  "complete": true,
  "operation": "start-logging",
  "error": "Could not create Trace Flags: LogType is required.: LogType",
  "stack": "Error: Could not create Trace Flags: LogType is required.: LogType\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\sfdc-client.js:931:20\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\promise\\lib\\core.js:33:15\n    at flush (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\asap\\asap.js:27:13)\n    at doNTCallback0 (node.js:416:9)\n    at process._tickCallback (node.js:345:13)",
  "promiseId": "5d1bd780-80e5-11e5-8ca3-dbcc6e0b7c0a"
}
```

**Comment by cipherstream** [comment]
I am having the exact same issue.  I've verified that the "log type" is set to debug in the settings (config?).
