### ISSUE TITLE
Experiencing "Uncaught TypeError: Cannot read property 'inFolder' of undefined" on version 1.3.1

### ISSUE THREAD

**Issue by SaiTejaswini** [joeferraro/MavensMate-Atom#295]

**Comment by iDev0urer** [comment]
I'm also getting this error. Here is the full trace: 

```
[March 21st 2016, 8:46:24 pm]
> Deploying resource bundle product-list.html
> Cannot read property 'inFolder' of undefined
{
  "id": "a6532dd0-efe0-11e5-a61f-81822b172884",
  "complete": true,
  "operation": "deploy-resource-bundle",
  "error": "Cannot read property 'inFolder' of undefined",
  "stack": "TypeError: Cannot read property 'inFolder' of undefined\n    at Object.defineProperty.get (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\file.js:213:18)\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\file.js:556:10\n    at arrayEach (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\lodash\\index.js:1289:13)\n    at Function.<anonymous> (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\lodash\\index.js:3345:13)\n    at Object.module.exports.createPackageSubscription (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\file.js:552:5)\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\resource-bundle.js:100:46\n    at tryCatch2 (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\util.js:53:21)\n    at Promise._resolveFromResolver (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:544:13)\n    at new Promise (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:82:37)\n    at ResourceBundleService.deploy (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\resource-bundle.js:87:10)\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\commands\\resource-bundle\\deploy-resource-bundle.js:25:19\n    at tryCatch2 (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\util.js:53:21)\n    at Promise._resolveFromResolver (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:544:13)\n    at new Promise (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:82:37)\n    at Command.execute (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\commands\\resource-bundle\\deploy-resource-bundle.js:22:10)\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\client.js:380:21",
  "promiseId": "a64ec100-efe0-11e5-9595-676994f2e52d"
}
```

**Comment by iDev0urer** [comment]
It seems as though I got it when I tried to deploy a resource bundle from a file within the bundle. It tried to deploy the file itself instead of the resource bundle
