### ISSUE TITLE
Uncaught Error: Cannot find module './_stream_duplex'

### ISSUE THREAD

**Issue by bullcitydave** [joeferraro/MavensMate-Atom#337]
[Enter steps to reproduce below:]

1. Had been experiencing a UI issue with MavensMate, saw that update was available
2. Installed 1.0.9

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.4
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v1.0.9

### Stack Trace

Uncaught Error: Cannot find module './_stream_duplex'

```
At module.js:341

Error: Cannot find module './_stream_duplex'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at BufferList.Readable (/Users/daveseidman/.atom/packages/MavensMate-Atom/node_modules/request/node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js:128:22)
    at BufferList.Duplex (/Users/daveseidman/.atom/packages/MavensMate-Atom/node_modules/request/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:43:12)
    at new BufferList (/Users/daveseidman/.atom/packages/MavensMate-Atom/node_modules/request/node_modules/bl/bl.js:32:16)
    at BufferList (/Users/daveseidman/.atom/packages/MavensMate-Atom/node_modules/request/node_modules/bl/bl.js:7:12)
    at Request.readResponseBody (/Users/daveseidman/.atom/packages/MavensMate-Atom/node_modules/request/request.js:1015:16)
    at Request.onRequestResponse (/Users/daveseidman/.atom/packages/MavensMate-Atom/node_modules/request/request.js:996:12)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:458:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at Socket.socketOnData (_http_client.js:348:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```

### Commands

```
     -0:33 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -0:00.4.0 mavensmate:open-mavensmate-ui (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-eslint",
      "react-redux-snippets",
      "apex-snippets"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_panel_height": 464
  }
}
```

### Installed Packages

```coffee
# User
apex-snippets, v0.6.1 (inactive)
atom-beautify, v0.29.9 (inactive)
atomic-ui, v1.5.2 (inactive)
colorblind-syntax, v1.1.2 (inactive)
flexible-ui, v0.9.0 (inactive)
git-time-machine, v1.5.3 (inactive)
linter, v1.11.14 (active)
linter-eslint, v7.2.4 (inactive)
MavensMate-Atom, v1.0.9 (active)
react, v0.15.0 (active)
react-redux-snippets, v0.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by bullcitydave** [comment]
Issue appears resolved after having rebooted, no other changes made. Perhaps a non-issue if no one else has reported.
