### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mainModule' of undefined

### ISSUE THREAD

**Issue by jdk243** [joeferraro/MavensMate-Atom#347]
1. Right click file in atom tree view
2. Under Mavensmate option, click refresh from server

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package 1.0.10

### Stack Trace

Uncaught TypeError: Cannot read property 'mainModule' of undefined

```
At /home/jaredkass/.atom/packages/MavensMate-Atom/lib/util.coffee:153

TypeError: Cannot read property 'mainModule' of undefined
  at Function.module.exports.MMUtil.treeView (/packages/MavensMate-Atom/lib/util.coffee:153:50)
  at Function.module.exports.MMUtil.getSelectedFiles (/packages/MavensMate-Atom/lib/util.coffee:74:23)
  at /packages/MavensMate-Atom/lib/mavensmate.coffee:233:38)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (<embedded>:18901:35)
  at CommandRegistry.handleCommandEvent (<embedded>:18639:65)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (<embedded>:18802:25)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (<embedded>:1554:34)
  at EventEmitter.outerCallback (<embedded>:2012:31)
  at emitThree (events.js:116:13)
  at EventEmitter.emit (events.js:194:7)

```

### Commands

```
  2x -0:49.1.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -0:27.4.0 mavensmate:refresh-selected-metadata (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-text.name.nuclide-file-tree-path)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-material-syntax 1.0.6 
atom-material-ui 1.3.10 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-modules 1.6.10 
busy-signal 1.4.3 
docblockr 0.10.5 
git-plus 7.8.0 
git-projects 1.17.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.66.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-flow 5.6.0 
linter-ui-default 1.2.4 
MavensMate-Atom 1.0.10 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
monokai-seti 0.9.0 
nuclide 0.232.0 
open-recent 5.0.0 
package-list 0.1.2 
pigments 0.39.1 
redux-snippets 0.2.2 
seti-ui 1.9.0 
```

**Comment by JKCooper2** [comment]
Maybe double check you are actually selecting the file in tree view. I had this same error and it was because I'd installed nuclide (which I can see you have as well) and was trying to use MavensMate commands from their project view, rather than the main tree-view package
