### ISSUE TITLE
Failed to activate the MavensMate-Atom-master package

### ISSUE THREAD

**Issue by joxe2drums** [joeferraro/MavensMate-Atom#349]
When opening Atom IDE:

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [MavensMate-Atom-master](https://github.com/joeferraro/MavensMate-Atom) package 1.1.0

### Stack Trace

Failed to activate the MavensMate-Atom-master package

```
At Cannot read property 'mm_workspace' of undefined

TypeError: Cannot read property 'mm_workspace' of undefined
    at Object.unsetDeprecatedSettings (/packages/MavensMate-Atom/lib/main.coffee:83:10)
    at Object.activate (/packages/MavensMate-Atom/lib/main.coffee:58:6)
    at Package.activateNow (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:200:20)
    at Package.activate (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.24.0/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.24.0/resources/app/src/atom-environment.js:841:27)
```

### Commands

```
```

### Non-Core Packages

```
apex-snippets 0.6.1 
atom-beautify 0.30.9 
atom-typescript 12.2.0 
MavensMate-Atom 1.1.0 
```

**Comment by joxe2drums** [comment]
Resolved by uninstalling and installing again
